<!DOCTYPE html><html lang="{{ app()->getLocale() }}" dir="{{ app()->isLocale('ar') ? 'rtl' : 'ltr' }}"><head>
@include('partials.application-icons')<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ __('footer.faqs') }} · {{ app(\App\Services\SettingService::class)->name() }}</title>
@vite(['resources/css/app.css','resources/js/app.js'])
<style>
body{margin:0;background:#f6f8fc;color:#10213b;font-family:"Segoe UI",Tahoma,Arial,sans-serif}.faq-nav{height:76px;border-bottom:1px solid #e5eaf0;background:#ffffffed;display:flex;align-items:center}.faq-nav>div{width:min(1160px,calc(100% - 32px));margin:auto;display:flex;align-items:center;justify-content:space-between}.faq-brand{display:flex;align-items:center;gap:.7rem;color:#071d3e;text-decoration:none}.faq-brand img{width:43px;height:43px;object-fit:contain}.faq-brand strong{font-size:1rem}.faq-back{padding:.65rem 1rem;border:1px solid #dfe5ed;border-radius:.75rem;color:#405068;text-decoration:none;font-size:.82rem;font-weight:700}.faq-hero{position:relative;overflow:hidden;padding:6rem 1rem 8rem;text-align:center;color:white;background:linear-gradient(145deg,#071d3e,#0b3269)}.faq-hero:after{position:absolute;inset:0;content:'';opacity:.18;background-image:radial-gradient(#fff 1px,transparent 1px);background-size:24px 24px;mask-image:linear-gradient(#000,transparent)}.faq-hero>*{position:relative;z-index:1}.faq-hero span{color:#fbbf24;font-size:.72rem;font-weight:900;letter-spacing:.14em}.faq-hero h1{max-width:750px;margin:1rem auto;font-size:clamp(2.3rem,6vw,4.6rem);line-height:1.08;letter-spacing:-.04em}.faq-hero p{max-width:630px;margin:auto;color:#b9c8db;line-height:1.8}.faq-wrap{position:relative;z-index:2;width:min(850px,calc(100% - 28px));margin:-4rem auto 0}.faq-list{display:grid;gap:.9rem}.faq-item{overflow:hidden;border:1px solid #e2e8f0;border-radius:1rem;background:#fff;box-shadow:0 12px 35px rgba(7,29,62,.07)}.faq-item summary{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:1.3rem 1.45rem;cursor:pointer;list-style:none;font-weight:800}.faq-item summary::-webkit-details-marker{display:none}.faq-item summary i{display:grid;width:1.8rem;height:1.8rem;place-items:center;flex:none;border-radius:50%;background:#fff4db;color:#b87300;font-style:normal;transition:.2s}.faq-item[open] summary i{transform:rotate(45deg);background:#f59e0b;color:#fff}.faq-answer{padding:0 1.45rem 1.4rem;color:#667287;line-height:1.9;border-top:1px solid #f0f2f5}.faq-answer p{margin:1.1rem 0 0}.faq-empty{padding:3rem;text-align:center;border-radius:1rem;background:white;color:#667287}.faq-help{display:flex;align-items:center;justify-content:space-between;gap:2rem;margin-top:2rem;padding:1.7rem 2rem;border-radius:1.1rem;background:#fff0cf}.faq-help h2{margin:0 0 .3rem;font-size:1.2rem}.faq-help p{margin:0;color:#74613b}.faq-help a{padding:.85rem 1.2rem;border-radius:.75rem;background:#071d3e;color:#fff;text-decoration:none;font-weight:800;font-size:.85rem}@media(max-width:600px){.faq-hero{padding-top:4rem}.faq-help{align-items:stretch;flex-direction:column}.faq-help a{text-align:center}}
</style></head><body>
<nav class="faq-nav"><div><a class="faq-brand" href="{{ route('home') }}"><img src="{{ app(\App\Services\SettingService::class)->logoUrl() }}" alt=""><strong>{{ app(\App\Services\SettingService::class)->name() }}</strong></a><a class="faq-back" href="{{ route('home') }}">{{ __('footer.home') }}</a></div></nav>
<header class="faq-hero"><span>{{ __('footer.faq.eyebrow') }}</span><h1>{{ __('footer.faq.title') }}</h1><p>{{ __('footer.faq.description') }}</p></header>
<main class="faq-wrap"><section class="faq-list">
@forelse($faqs as $faq)<details class="faq-item" @if($loop->first) open @endif><summary><span>{{ $faq->question }}</span><i>+</i></summary><div class="faq-answer"><p>{{ $faq->answer }}</p></div></details>@empty<div class="faq-empty">{{ __('footer.faq.empty') }}</div>@endforelse
</section><section class="faq-help"><div><h2>{{ __('footer.faq.still_need_help') }}</h2><p>{{ __('footer.faq.help_text') }}</p></div><a href="{{ route('contact.index') }}">{{ __('footer.faq.contact_button') }}</a></section></main>
@include('partials.site-footer')</body></html>
