<x-filament-panels::page>
@include('filament.pages.partials.payment-monitor-styles')
<div class="pm-shell">
<section class="pm-hero"><div class="pm-hero-copy"><span class="pm-kicker"><i></i> {{ __('lms.webhooks.hero.kicker') }}</span><h2>{{ __('lms.webhooks.hero.title') }}</h2><p>{{ __('lms.webhooks.hero.description') }}</p></div><div class="pm-health"><span class="pm-health-dot"></span><div><small>{{ __('lms.webhooks.listener') }}</small><strong>{{ __('lms.webhooks.ready') }}</strong></div></div></section>
<section class="pm-stats"><article class="pm-stat"><span class="pm-stat-label">{{ __('lms.webhooks.stats.events_received') }}</span><strong class="pm-stat-value">{{ number_format($stats['total']) }}</strong><small class="pm-stat-note">{{ __('lms.webhooks.stats.events_received_note') }}</small></article><article class="pm-stat" style="--stat-color:#10b981"><span class="pm-stat-label">{{ __('lms.webhooks.stats.processed') }}</span><strong class="pm-stat-value">{{ number_format($stats['processed']) }}</strong><small class="pm-stat-note">{{ __('lms.webhooks.stats.processed_note') }}</small></article><article class="pm-stat" style="--stat-color:#ef4444"><span class="pm-stat-label">{{ __('lms.webhooks.stats.needs_attention') }}</span><strong class="pm-stat-value">{{ number_format($stats['attention']) }}</strong><small class="pm-stat-note">{{ __('lms.webhooks.stats.needs_attention_note') }}</small></article><article class="pm-stat" style="--stat-color:#8b5cf6"><span class="pm-stat-label">{{ __('lms.webhooks.stats.processing_attempts') }}</span><strong class="pm-stat-value">{{ number_format($stats['retries']) }}</strong><small class="pm-stat-note">{{ __('lms.webhooks.stats.processing_attempts_note') }}</small></article></section>
<section class="pm-toolbar"><label class="pm-search"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-width="2" d="m21 21-4.4-4.4m2.4-5.1a7.5 7.5 0 1 1-15 0 7.5 7.5 0 0 1 15 0Z"/></svg><input class="pm-input" wire:model.live.debounce.350ms="search" placeholder="{{ __('lms.webhooks.search_placeholder') }}"></label><select class="pm-select" wire:model.live="status"><option value="all">{{ __('lms.webhooks.status.all') }}</option><option value="received">{{ __('lms.webhooks.status.received') }}</option><option value="processing">{{ __('lms.webhooks.status.processing') }}</option><option value="processed">{{ __('lms.webhooks.status.processed') }}</option><option value="failed">{{ __('lms.webhooks.status.failed') }}</option><option value="rejected">{{ __('lms.webhooks.status.rejected') }}</option></select><select class="pm-select" wire:model.live="perPage"><option value="12">12 {{ __('lms.payments.per_page') }}</option><option value="24">24 {{ __('lms.payments.per_page') }}</option><option value="48">48 {{ __('lms.payments.per_page') }}</option></select></section>
<div class="pm-stream" wire:loading.class="opacity-50">@forelse($events as $event)<article class="pm-card" wire:key="event-{{ $event->id }}"><div class="pm-icon"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor"><path d="m13 2-9 12h7l-1 8 9-12h-7l1-8Z"/></svg></div><div class="pm-main"><div class="pm-titleline"><strong class="pm-title">{{ $event->event_type }}</strong><span class="pm-badge pm-badge--{{ $event->status }}">{{ $event->status }}</span></div><div class="pm-meta"><span>{{ __('lms.webhooks.transaction_label') }} <b>#{{ $event->provider_transaction_id ?? '—' }}</b></span><span>{{ __('lms.webhooks.order_label') }} <b>{{ $event->order?->number ?? $event->provider_order_id ?? __('lms.payments.unavailable') }}</b></span><span>{{ __('lms.webhooks.provider_label') }} <b>{{ ucfirst($event->provider) }}</b></span><span>{{ __('lms.webhooks.deliveries_label') }} <b>{{ $event->delivery_count }}</b></span><span>{{ __('lms.webhooks.attempts_label') }} <b>{{ $event->processing_attempts }}</b></span></div></div><div class="pm-side"><strong class="pm-amount">{{ __('lms.webhooks.event_label') }} #{{ $event->id }}</strong><time class="pm-date">{{ $event->received_at?->diffForHumans() }}</time></div>@if($event->failure_reason)<div class="pm-error">{{ $event->failure_reason }}</div>@endif</article>@empty<div class="pm-empty"><div><span>ϟ</span><h3>{{ __('lms.webhooks.empty.title') }}</h3><p>{{ __('lms.webhooks.empty.description') }}</p></div></div>@endforelse</div>
@if($events->hasPages())<div class="pm-pagination"><x-filament::pagination :paginator="$events" /></div>@endif
</div>
</x-filament-panels::page>
