<x-filament-panels::page>
@include('filament.pages.partials.payment-monitor-styles')
<div class="pm-shell">
<section class="pm-hero"><div class="pm-hero-copy"><span class="pm-kicker"><i></i> {{ __('lms.payments.hero.kicker') }}</span><h2>{{ __('lms.payments.hero.title') }}</h2><p>{{ __('lms.payments.hero.description') }}</p></div><div class="pm-health"><span class="pm-health-dot"></span><div><small>{{ __('lms.payments.gateway_status') }}</small><strong>{{ __('lms.payments.monitoring_active') }}</strong></div></div></section>
<section class="pm-stats"><article class="pm-stat"><span class="pm-stat-label">{{ __('lms.payments.stats.all_transactions') }}</span><strong class="pm-stat-value">{{ number_format($stats['total']) }}</strong><small class="pm-stat-note">{{ __('lms.payments.stats.all_transactions_note') }}</small></article><article class="pm-stat" style="--stat-color:#10b981"><span class="pm-stat-label">{{ __('lms.payments.stats.successful') }}</span><strong class="pm-stat-value">{{ number_format($stats['paid']) }}</strong><small class="pm-stat-note">{{ __('lms.payments.stats.successful_note') }}</small></article><article class="pm-stat" style="--stat-color:#ef4444"><span class="pm-stat-label">{{ __('lms.payments.stats.needs_attention') }}</span><strong class="pm-stat-value">{{ number_format($stats['attention']) }}</strong><small class="pm-stat-note">{{ __('lms.payments.stats.needs_attention_note') }}</small></article><article class="pm-stat" style="--stat-color:#f59e0b"><span class="pm-stat-label">{{ __('lms.payments.stats.revenue') }}</span><strong class="pm-stat-value">{{ number_format($stats['revenue']/100,2) }}</strong><small class="pm-stat-note">{{ __('lms.payments.stats.revenue_note') }}</small></article></section>
<section class="pm-toolbar"><label class="pm-search"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-width="2" d="m21 21-4.4-4.4m2.4-5.1a7.5 7.5 0 1 1-15 0 7.5 7.5 0 0 1 15 0Z"/></svg><input class="pm-input" wire:model.live.debounce.350ms="search" placeholder="{{ __('lms.payments.search_placeholder') }}"></label><select class="pm-select" wire:model.live="status"><option value="all">{{ __('lms.payments.status.all') }}</option><option value="paid">{{ __('lms.payments.status.paid') }}</option><option value="pending">{{ __('lms.payments.status.pending') }}</option><option value="failed">{{ __('lms.payments.status.failed') }}</option><option value="rejected">{{ __('lms.payments.status.rejected') }}</option><option value="refunded">{{ __('lms.payments.status.refunded') }}</option><option value="received">{{ __('lms.payments.status.received') }}</option></select><select class="pm-select" wire:model.live="perPage"><option value="12">12 {{ __('lms.payments.per_page') }}</option><option value="24">24 {{ __('lms.payments.per_page') }}</option><option value="48">48 {{ __('lms.payments.per_page') }}</option></select></section>
<div class="pm-stream" wire:loading.class="opacity-50">@forelse($transactions as $transaction)<article class="pm-card" wire:key="transaction-{{ $transaction->id }}"><div class="pm-icon"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor"><rect x="3" y="5" width="18" height="14" rx="3"/><path d="M3 10h18M7 15h3"/></svg></div><div class="pm-main"><div class="pm-titleline"><strong class="pm-title">#{{ $transaction->provider_transaction_id }}</strong><span class="pm-badge pm-badge--{{ $transaction->status }}">{{ $transaction->status }}</span></div><div class="pm-meta"><span>{{ __('lms.payments.order_label') }} <b>{{ $transaction->order?->number ?? __('lms.payments.unavailable') }}</b></span><span>{{ __('lms.payments.provider_label') }} <b>{{ ucfirst($transaction->provider) }}</b></span>@if($transaction->order?->user)<span>{{ __('lms.payments.customer_label') }} <b>{{ $transaction->order->user->name }}</b></span>@endif<span>{{ __('lms.payments.integration_label') }} <b>{{ $transaction->integration_id ?? '—' }}</b></span></div></div><div class="pm-side"><strong class="pm-amount">{{ $transaction->amount_cents!==null?number_format($transaction->amount_cents/100,2):'—' }} {{ $transaction->currency }}</strong><time class="pm-date">{{ $transaction->received_at?->diffForHumans() }}</time></div>@if($transaction->failure_reason)<div class="pm-error">{{ $transaction->failure_reason }}</div>@endif</article>@empty<div class="pm-empty"><div><span>◎</span><h3>{{ __('lms.payments.empty.title') }}</h3><p>{{ __('lms.payments.empty.description') }}</p></div></div>@endforelse</div>
@if($transactions->hasPages())<div class="pm-pagination"><x-filament::pagination :paginator="$transactions" /></div>@endif
</div>
</x-filament-panels::page>
