@php
    $videos = $course->sections->flatMap->videos;
    $totalLessons = $videos->count();
    $freeLessons = $videos->where('is_free', true)->count();
    $effectivePrice = $course->price_after_discount ?: $course->price;
    $formatDuration = static fn ($seconds) => __('lms.course_show.duration', ['hours' => intdiv((int) $seconds, 3600), 'minutes' => str_pad((string) intdiv((int) $seconds % 3600, 60), 2, '0', STR_PAD_LEFT)]);
@endphp
<main dir="{{ app()->isLocale('ar') ? 'rtl' : 'ltr' }}">
    @if($notice)
        <div class="cp-notice {{ $noticeType }}" role="status" wire:key="course-notice"><span>{{ $noticeType === 'success' ? '✓' : '!' }}</span><p>{{ $notice }}</p><button type="button" wire:click="$set('notice', null)" aria-label="{{ __('lms.course_show.close') }}">×</button></div>
    @endif
    <section class="cp-hero"><div class="cp-container cp-hero-grid"><div>
        <div class="cp-crumb"><a href="{{ route('home') }}">{{ __('lms.course_show.home') }}</a><span>›</span><span>{{ $course->category?->name }}</span></div>
        <span class="cp-pill">{{ __('lms.course_show.levels.'.$course->level) }} · {{ strtoupper($course->lang) }}</span><h1>{{ $course->title }}</h1><p>{{ $course->description }}</p>
        <div class="cp-author"><span>{{ mb_substr($course->instructor?->name ?? __('lms.course_show.instructor_initial'), 0, 1) }}</span><div><small>{{ __('lms.course_show.created_by') }}</small><b>{{ $course->instructor?->name }}</b></div></div>
        <div class="cp-hero-meta"><span>★ {{ __('lms.course_show.rating', ['rating' => number_format((float) ($course->course_reviews_avg_rating ?? 0), 1)]) }}</span><span>◉ {{ trans_choice('lms.course_show.learners', $course->students_count, ['count' => number_format($course->students_count)]) }}</span><span>◷ {{ $formatDuration($course->duration) }}</span></div>
    </div><div class="cp-cover">@if($this->thumbnailUrl())<img src="{{ $this->thumbnailUrl() }}" alt="{{ $course->title }}">@else<div class="cp-cover-fallback">{{ mb_substr($course->title, 0, 1) }}</div>@endif<span>{{ __('lms.course_show.preview_available') }}</span></div></div></section>

    <section class="cp-page"><div class="cp-container cp-layout"><div class="cp-main">
        @if($this->selectedVideo)
            <section class="cp-panel cp-player-panel" wire:key="player-{{ $this->selectedVideo->id }}"><div class="cp-panel-head"><div><span>{{ __('lms.course_show.free_preview') }}</span><h2>{{ $this->selectedVideo->title }}</h2></div><small>{{ $formatDuration($this->selectedVideo->duration) }}</small></div><x-course-video-player :video="$this->selectedVideo" :course="$course" :poster="$this->thumbnailUrl()" :watermark="config('app.name')" /></section>
        @endif
        <section class="cp-panel"><div class="cp-panel-head"><div><span>{{ __('lms.course_show.what_you_will_learn') }}</span><h2>{{ __('lms.course_show.skills_heading') }}</h2></div></div><div class="cp-goals">@forelse($course->goals as $goal)<div><i>✓</i><span>{{ $goal->goal }}</span></div>@empty<p>{{ __('lms.course_show.no_goals') }}</p>@endforelse</div></section>
        <section class="cp-panel"><div class="cp-panel-head"><div><span>{{ __('lms.course_show.course_content') }}</span><h2>{{ __('lms.course_show.content_summary', ['sections' => $course->sections->count(), 'lessons' => $totalLessons]) }}</h2></div><small>{{ trans_choice('lms.course_show.free_previews', $freeLessons, ['count' => $freeLessons]) }}</small></div><div class="cp-curriculum">@forelse($course->sections as $section)<details @if($loop->first) open @endif><summary><b>{{ str_pad($loop->iteration, 2, '0', STR_PAD_LEFT) }}. {{ $section->title }}</b><span>{{ trans_choice('lms.course_show.lessons', $section->videos->count(), ['count' => $section->videos->count()]) }}</span></summary><div>@foreach($section->videos as $video)<button type="button" wire:click="selectVideo({{ $video->id }})" class="{{ $selectedVideoId === $video->id ? 'active' : '' }}"><i>{{ $video->is_free || $this->hasPurchased ? '▶' : '🔒' }}</i><span><b>{{ $video->title }}</b><small>{{ $formatDuration($video->duration) }}</small></span>@if($video->is_free)<em>{{ __('lms.course_show.preview') }}</em>@endif</button>@endforeach</div></details>@empty<p>{{ __('lms.course_show.no_curriculum') }}</p>@endforelse</div></section>
        <section class="cp-panel cp-instructor"><div class="cp-panel-head"><div><span>{{ __('lms.course_show.your_instructor') }}</span><h2>{{ __('lms.course_show.learn_from_experience') }}</h2></div></div><div class="cp-instructor-row"><div class="cp-avatar">{{ mb_substr($course->instructor?->name ?? __('lms.course_show.instructor_initial'), 0, 1) }}</div><div><h3>{{ $course->instructor?->name }}</h3><p>{{ $course->instructor?->small_description ?: $course->instructor?->bio ?: __('lms.course_show.instructor_fallback') }}</p></div></div></section>
        <section class="cp-panel" id="reviews"><div class="cp-panel-head"><div><span>{{ __('lms.course_show.student_reviews') }}</span><h2>{{ __('lms.course_show.out_of_five', ['rating' => number_format((float) ($course->course_reviews_avg_rating ?? 0), 1)]) }}</h2></div><small>{{ trans_choice('lms.course_show.reviews', $course->course_reviews_count, ['count' => $course->course_reviews_count]) }}</small></div><div class="cp-review-grid">@foreach($course->courseReviews->where('is_approved', true)->take(6) as $review)<article><div>★★★★★</div><p>“{{ $review->comment }}”</p><b>{{ $review->user?->name ?? __('lms.course_show.learner') }}</b></article>@endforeach</div>
            <form wire:submit="saveRating" class="cp-rating-form"><h3>{{ __('lms.course_show.rate_course') }}</h3><div wire:ignore><select class="course-rating-input" x-on:change="$wire.set('rating', Number($event.target.value))" data-options='{"maxStars":5,"clearable":false,"tooltip":false}'>@for($i = 1; $i <= 5; $i++)<option value="{{ $i }}" @selected($rating === $i)>{{ $i }}</option>@endfor</select></div><textarea wire:model="comment" rows="3" placeholder="{{ __('lms.course_show.share_experience') }}"></textarea>@error('rating')<small>{{ $message }}</small>@enderror @error('comment')<small>{{ $message }}</small>@enderror<button type="submit">{{ __('lms.course_show.save_rating') }}</button></form>
        </section>
    </div>
    <aside class="cp-sidebar"><div class="cp-buy-card"><span class="cp-price">{{ (float) $effectivePrice > 0 ? number_format((float) $effectivePrice, 2).' EGP' : __('lms.course_show.free') }}</span>@if($course->price_after_discount)<del>{{ number_format((float) $course->price, 2) }} EGP</del>@endif @if($this->hasPurchased)<a class="cp-primary" href="{{ route('courses.learn', $course) }}">{{ __('lms.course_show.go_to_course') }}</a>@else<button class="cp-primary" type="button" wire:click="enroll">{{ __('lms.course_show.enroll_now') }}</button>@endif<button type="button" wire:click="toggleWishlist">{{ $this->isWishlisted ? '♥ '.__('lms.course_show.saved_to_wishlist') : '♡ '.__('lms.course_show.save_for_later') }}</button><hr><h3>{{ __('lms.course_show.includes') }}</h3><ul><li>▣ {{ trans_choice('lms.course_show.focused_lessons', $totalLessons, ['count' => $totalLessons]) }}</li><li>◷ {{ __('lms.course_show.on_demand_video', ['duration' => $formatDuration($course->duration)]) }}</li><li>♾ {{ __('lms.course_show.lifetime_access') }}</li><li>✓ {{ __('lms.course_show.certificate') }}</li><li>⌁ {{ __('lms.course_show.any_device') }}</li></ul></div><div class="cp-requirements"><h3>{{ __('lms.course_show.requirements') }}</h3><ul>@forelse($course->requirements as $requirement)<li>{{ $requirement->content }}</li>@empty<li>{{ __('lms.course_show.no_requirements') }}</li>@endforelse</ul></div></aside>
    </div></section>
</main>
