<x-filament-panels::page>
    @php
        $course = $this->getRecord();
        $videos = $course->sections->flatMap->videos;
        $attachments = $videos->flatMap->attachments;
        $sales = $course->purchases->where('payment_status', 'completed');
        $reviews = $course->reviews->where('is_approved', true);
        $featured = $videos->firstWhere('url', '!=', null);
        $time = static function ($value): string {
            $s = (int) $value;
            if ($s < 1) return __('lms.instructor.course_view.pending_analysis');
            return (intdiv($s, 3600) ? intdiv($s, 3600).'h ' : '').intdiv($s % 3600, 60).'m '.($s % 60).'s';
        };
        $size = static function ($bytes): string {
            if (! $bytes) return '';
            $i = min((int) floor(log($bytes, 1024)), 3);
            return number_format($bytes / 1024 ** $i, $i ? 1 : 0).' '.['B','KB','MB','GB'][$i];
        };
    @endphp

    <style>
        .premium-course{--gold:#f59e0b;--orange:#fb923c;--ink:#111827}.dark .premium-course{--ink:#f9fafb}
        .pc-glass{background:rgba(255,255,255,.88);border:1px solid rgba(255,255,255,.7);box-shadow:0 20px 60px rgba(15,23,42,.11);backdrop-filter:blur(18px)}
        .dark .pc-glass{background:rgba(17,24,39,.84);border-color:rgba(255,255,255,.09);box-shadow:0 24px 70px rgba(0,0,0,.36)}
        .pc-hero{position:relative;isolation:isolate;overflow:hidden;min-height:450px;border-radius:30px;background:#111827;box-shadow:0 32px 80px rgba(15,23,42,.28)}
        .pc-hero:after{content:"";position:absolute;inset:0;z-index:-1;background:linear-gradient(90deg,rgba(3,7,18,.98),rgba(3,7,18,.80) 50%,rgba(3,7,18,.22))}
        .pc-orb{position:absolute;border-radius:999px;filter:blur(3px);opacity:.45;pointer-events:none}
        .pc-title{display:flex;align-items:center;gap:12px;color:var(--ink);font-size:1.22rem;font-weight:900}.pc-title:before{content:"";width:5px;height:27px;border-radius:99px;background:linear-gradient(var(--gold),var(--orange))}
        .pc-stat{position:relative;overflow:hidden;transition:.25s}.pc-stat:hover{transform:translateY(-6px);box-shadow:0 22px 50px rgba(15,23,42,.14)}.pc-stat:after{content:"";position:absolute;right:-35px;bottom:-38px;width:110px;height:110px;border-radius:50%;background:var(--accent);opacity:.1}
        .pc-icon{display:grid;width:48px;height:48px;place-items:center;border-radius:16px;color:var(--accent);background:color-mix(in srgb,var(--accent) 14%,transparent);font-size:20px;font-weight:900}
        .pc-lesson{border:1px solid rgba(148,163,184,.2);border-radius:20px;background:rgba(248,250,252,.72);transition:.25s}.dark .pc-lesson{background:rgba(255,255,255,.035);border-color:rgba(255,255,255,.08)}.pc-lesson:hover{border-color:rgba(245,158,11,.5);box-shadow:0 14px 35px rgba(15,23,42,.09)}
        .pc-progress{height:8px;overflow:hidden;border-radius:99px;background:rgba(148,163,184,.2)}.pc-progress i{display:block;height:100%;border-radius:inherit;background:linear-gradient(90deg,#f59e0b,#fb923c);box-shadow:0 0 14px rgba(245,158,11,.45)}
        @media(max-width:768px){.pc-hero{min-height:540px;border-radius:22px}.pc-hero:after{background:linear-gradient(0deg,rgba(3,7,18,.98),rgba(3,7,18,.48))}}
    </style>

    <div class="premium-course space-y-7">
        <section class="pc-hero flex items-end p-7 sm:p-10 lg:p-12">
            @if($course->thumbnail)<img src="{{ $this->r2Url($course->thumbnail) }}" alt="" class="absolute inset-0 -z-10 h-full w-full object-cover">@endif
            <i class="pc-orb -right-16 -top-20 h-64 w-64 bg-amber-400"></i><i class="pc-orb bottom-4 right-1/3 h-32 w-32 bg-orange-500"></i>
            <div class="max-w-3xl text-white">
                <div class="mb-5 flex flex-wrap gap-2 text-xs font-extrabold uppercase tracking-wider"><span class="rounded-full bg-amber-400 px-3 py-1.5 text-gray-950">{{ $course->category?->name ?? __('lms.instructor.course_view.uncategorized') }}</span><span class="rounded-full border border-white/20 bg-white/10 px-3 py-1.5 backdrop-blur">{{ ucfirst($course->level) }}</span><span class="rounded-full border border-white/20 bg-white/10 px-3 py-1.5 backdrop-blur">{{ strtoupper($course->lang) }}</span><span class="rounded-full px-3 py-1.5 {{ $course->is_published ? 'bg-emerald-500/90' : 'bg-rose-500/90' }}">{{ $course->is_published ? __('lms.instructor.course_view.published') : __('lms.instructor.course_view.draft') }}</span></div>
                <h1 class="text-3xl font-black leading-tight sm:text-4xl lg:text-5xl">{{ $course->title }}</h1><p class="mt-5 max-w-2xl text-base leading-8 text-gray-200 sm:text-lg">{{ str($course->description)->limit(240) }}</p>
                <div class="mt-7 flex flex-wrap gap-5 text-sm text-gray-200"><span>◉ {{ $course->instructor?->name ?? __('lms.instructor.course_view.instructor') }}</span><span>▶ {{ $videos->count() }} {{ __('lms.instructor.course_view.lessons') }}</span><span>◷ {{ $time($course->duration) }}</span><span>★ {{ number_format((float)$reviews->avg('rating'),1) }}</span></div>
            </div>
            <div class="absolute bottom-9 right-9 hidden rounded-2xl border border-white/20 bg-black/30 p-5 text-right text-white backdrop-blur-md lg:block"><p class="text-xs uppercase tracking-widest text-gray-300">{{ __('lms.instructor.course_view.course_price') }}</p><p class="mt-1 text-3xl font-black">{{ number_format((float)($course->price_after_discount ?: $course->price),2) }} EGP</p>@if($course->price_after_discount)<p class="text-sm text-gray-400 line-through">{{ number_format((float)$course->price,2) }} EGP</p>@endif</div>
        </section>

        <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            @foreach([[__('lms.instructor.course_view.students'),number_format((int)$course->students_count),'♟','#3b82f6'],[__('lms.instructor.course_view.completed_sales'),$sales->count(),'✓','#10b981'],[__('lms.instructor.course_view.revenue'),number_format((float)$sales->sum('price'),2).' EGP','EGP','#f59e0b'],[__('lms.instructor.course_view.wishlists'),$course->wishlists->count(),'♡','#ec4899']] as [$label,$value,$icon,$color])
                <div class="pc-stat pc-glass rounded-2xl p-5" style="--accent:{{ $color }}"><div class="flex items-center justify-between"><span class="pc-icon">{{ $icon }}</span><span class="text-xs font-bold uppercase tracking-wider text-gray-400">{{ __('lms.instructor.course_view.live') }}</span></div><p class="mt-5 text-2xl font-black text-gray-950 dark:text-white">{{ $value }}</p><p class="mt-1 text-sm text-gray-500">{{ $label }}</p></div>
            @endforeach
        </section>

        <section class="grid gap-7 xl:grid-cols-3">
            <main class="space-y-7 xl:col-span-2">
                @if($featured)<div class="pc-glass overflow-hidden rounded-3xl"><div class="flex items-center justify-between gap-4 p-6"><div><p class="text-xs font-bold uppercase tracking-widest text-amber-500">{{ __('lms.instructor.course_view.featured_lesson') }}</p><h2 class="mt-1 text-xl font-black text-gray-950 dark:text-white">{{ $featured->title }}</h2></div><span class="rounded-xl bg-gray-100 px-3 py-2 text-xs font-bold text-gray-500 dark:bg-white/5">{{ $time($featured->duration) }}</span></div><x-course-video-player :video="$featured" :course="$course" :poster="$course->thumbnail ? $this->r2Url($course->thumbnail) : null" watermark="{{ config('app.name') }}" retryable /></div>@endif

                <div class="pc-glass rounded-3xl p-5 sm:p-7"><h2 class="pc-title">{{ __('lms.instructor.course_view.course_curriculum') }}</h2><p class="mt-2 text-sm text-gray-500">{{ $course->sections->count() }} {{ __('lms.instructor.course_view.sections') }} · {{ $videos->count() }} {{ __('lms.instructor.course_view.lessons') }} · {{ $attachments->count() }} {{ __('lms.instructor.course_view.resources') }}</p>
                    <div class="mt-6 space-y-4">@forelse($course->sections as $section)
                        <div x-data="{open:{{ $loop->first ? 'true' : 'false' }}}" class="overflow-hidden rounded-2xl border border-gray-200 dark:border-white/10"><button type="button" @click="open=!open" class="flex w-full items-center justify-between gap-4 bg-gray-50 p-5 text-left dark:bg-white/5"><span class="flex min-w-0 items-center gap-4"><b class="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-amber-100 text-amber-700 dark:bg-amber-400/10 dark:text-amber-400">{{ str_pad($loop->iteration,2,'0',STR_PAD_LEFT) }}</b><span><strong class="block truncate text-gray-950 dark:text-white">{{ $section->title }}</strong><small class="text-gray-500">{{ $section->videos->count() }} {{ __('lms.instructor.course_view.lessons') }}</small></span></span><span class="text-xl text-gray-400 transition" :class="open&&'rotate-180'">⌄</span></button>
                            <div x-show="open" x-collapse class="space-y-3 p-4">@forelse($section->videos as $video)
                                <article class="pc-lesson p-4 sm:p-5"><div class="flex items-start gap-4"><span class="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-gray-950 text-xs text-white dark:bg-amber-400 dark:text-gray-950">▶</span><div class="min-w-0 flex-1"><div class="flex flex-wrap justify-between gap-2"><div><h3 class="font-bold text-gray-950 dark:text-white">{{ $video->title }}</h3><p class="mt-1 text-xs text-gray-500">{{ $time($video->duration) }} · {{ $video->is_free ? __('lms.instructor.course_view.free_preview') : __('lms.instructor.course_view.premium') }}</p></div><span class="h-fit rounded-full px-2.5 py-1 text-xs font-bold {{ $video->is_published ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-400' : 'bg-gray-200 text-gray-600 dark:bg-white/10 dark:text-gray-400' }}">{{ $video->is_published ? __('lms.instructor.course_view.published') : __('lms.instructor.course_view.hidden') }}</span></div>@if($video->description)<p class="mt-3 text-sm leading-6 text-gray-600 dark:text-gray-300">{{ $video->description }}</p>@endif</div></div>
                                <div class="mt-4"><x-course-video-player :video="$video" :course="$course" watermark="{{ config('app.name') }}" retryable /></div>
                                @if($video->attachments->isNotEmpty())<div class="mt-4 flex flex-wrap gap-2">@foreach($video->attachments as $attachment)<a href="{{ $this->r2Url($attachment->file_path) }}" target="_blank" rel="noopener" class="rounded-xl border border-gray-200 bg-white px-3 py-2 text-xs font-bold text-gray-700 transition hover:border-amber-400 hover:text-amber-600 dark:border-white/10 dark:bg-white/5 dark:text-gray-300">↧ {{ $attachment->file_name }} <span class="text-gray-400">{{ $size($attachment->file_size) }}</span></a>@endforeach</div>@endif</article>
                            @empty<p class="p-5 text-center text-sm text-gray-500">{{ __('lms.instructor.course_view.no_lessons') }}</p>@endforelse</div></div>
                    @empty<div class="rounded-2xl border border-dashed border-gray-300 p-10 text-center text-gray-500 dark:border-white/10">{{ __('lms.instructor.course_view.empty_curriculum') }}</div>@endforelse</div>
                </div>
            </main>

            <aside class="space-y-7">
                <div class="pc-glass rounded-3xl p-6"><h2 class="pc-title">{{ __('lms.instructor.course_view.at_glance') }}</h2><dl class="mt-6 space-y-4 text-sm">@foreach([[__('lms.instructor.course_view.category'),$course->category?->name],[__('lms.instructor.course_view.language'),__('lms.instructor.languages.'.$course->lang)],[__('lms.instructor.course_view.level'),__('lms.instructor.levels.'.$course->level)],[__('lms.instructor.course_view.duration'),$time($course->duration)],[__('lms.instructor.course_view.updated'),$course->updated_at?->translatedFormat('M d, Y')],[__('lms.instructor.course_view.course_id'),'#'.$course->id]] as [$label,$value])<div class="flex justify-between gap-4 border-b border-gray-100 pb-3 last:border-0 dark:border-white/5"><dt class="text-gray-500">{{ $label }}</dt><dd class="text-start font-bold text-gray-950 dark:text-white">{{ $value ?: '—' }}</dd></div>@endforeach</dl></div>
                <div class="pc-glass rounded-3xl p-6"><h2 class="pc-title">{{ __('lms.instructor.course_view.learning_goals') }}</h2><ul class="mt-5 space-y-3">@forelse($course->goals as $goal)<li class="flex gap-3 text-sm leading-6 text-gray-700 dark:text-gray-300"><b class="mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full bg-emerald-100 text-xs text-emerald-600 dark:bg-emerald-400/10">✓</b>{{ $goal->goal }}</li>@empty<li class="text-sm text-gray-500">{{ __('lms.instructor.course_view.no_goals') }}</li>@endforelse</ul></div>
                <div class="pc-glass rounded-3xl p-6"><h2 class="pc-title">{{ __('lms.instructor.course_view.requirements') }}</h2><ul class="mt-5 space-y-3">@forelse($course->requirements as $requirement)<li class="flex gap-3 text-sm leading-6 text-gray-700 dark:text-gray-300"><b class="text-amber-500">•</b>{{ $requirement->content }}</li>@empty<li class="text-sm text-gray-500">{{ __('lms.instructor.course_view.no_requirements') }}</li>@endforelse</ul></div>
            </aside>
        </section>

        <section class="grid gap-7 xl:grid-cols-2">
            <div class="pc-glass overflow-hidden rounded-3xl"><header class="flex items-center justify-between border-b border-gray-100 p-6 dark:border-white/5"><h2 class="pc-title">{{ __('lms.instructor.course_view.student_reviews') }}</h2><strong class="text-2xl text-amber-500">{{ number_format((float)$reviews->avg('rating'),1) }} ★</strong></header><div class="max-h-[500px] divide-y divide-gray-100 overflow-y-auto dark:divide-white/5">@forelse($course->reviews as $review)<article class="p-6"><div class="flex justify-between gap-4"><div><h3 class="font-bold text-gray-950 dark:text-white">{{ $review->user?->name ?? __('lms.instructor.course_view.deleted_user') }}</h3><small class="text-gray-400">{{ $review->created_at?->diffForHumans() }}</small></div><span class="text-amber-400">{{ str_repeat('★',(int)$review->rating) }}<i class="not-italic text-gray-300">{{ str_repeat('★',5-(int)$review->rating) }}</i></span></div><p class="mt-4 text-sm leading-6 text-gray-600 dark:text-gray-300">{{ $review->comment ?: __('lms.instructor.course_view.no_comment') }}</p></article>@empty<p class="p-10 text-center text-gray-500">{{ __('lms.instructor.course_view.no_reviews') }}</p>@endforelse</div></div>
            <div class="pc-glass overflow-hidden rounded-3xl"><header class="border-b border-gray-100 p-6 dark:border-white/5"><h2 class="pc-title">{{ __('lms.instructor.course_view.student_progress') }}</h2><p class="mt-2 text-sm text-gray-500">{{ __('lms.instructor.course_view.latest_engagement') }}</p></header><div class="max-h-[500px] divide-y divide-gray-100 overflow-y-auto dark:divide-white/5">@forelse($course->progress as $item)<article class="p-6"><div class="flex items-center justify-between gap-4"><div class="flex items-center gap-3"><b class="grid h-11 w-11 place-items-center rounded-full bg-gradient-to-br from-amber-400 to-orange-500 text-white">{{ strtoupper(substr($item->user?->name ?? 'U',0,1)) }}</b><div><h3 class="font-bold text-gray-950 dark:text-white">{{ $item->user?->name ?? __('lms.instructor.course_view.deleted_user') }}</h3><small class="text-gray-400">{{ $item->last_accessed_at?->diffForHumans() ?? __('lms.instructor.course_view.never_accessed') }}</small></div></div><strong class="text-amber-500">{{ $item->progress }}%</strong></div><div class="pc-progress mt-4"><i style="width:{{ min(100,max(0,$item->progress)) }}%"></i></div></article>@empty<p class="p-10 text-center text-gray-500">{{ __('lms.instructor.course_view.no_progress') }}</p>@endforelse</div></div>
        </section>

        <section class="pc-glass overflow-hidden rounded-3xl"><header class="flex flex-wrap items-center justify-between gap-3 border-b border-gray-100 p-6 dark:border-white/5"><div><h2 class="pc-title">{{ __('lms.instructor.course_view.recent_enrollments') }}</h2><p class="mt-2 text-sm text-gray-500">{{ __('lms.instructor.course_view.purchase_activity') }}</p></div><span class="rounded-full bg-emerald-100 px-3 py-1 text-sm font-bold text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-400">{{ $sales->count() }} {{ __('lms.common.completed') }}</span></header><div class="overflow-x-auto"><table class="w-full text-start text-sm"><thead class="bg-gray-50 text-xs uppercase tracking-wider text-gray-500 dark:bg-white/5"><tr><th class="px-6 py-4">{{ __('lms.instructor.course_view.student_col') }}</th><th class="px-6 py-4">{{ __('lms.instructor.course_view.amount_col') }}</th><th class="px-6 py-4">{{ __('lms.instructor.course_view.coupon_col') }}</th><th class="px-6 py-4">{{ __('lms.instructor.course_view.status_col') }}</th><th class="px-6 py-4">{{ __('lms.instructor.course_view.date_col') }}</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-white/5">@forelse($course->purchases as $purchase)<tr class="text-gray-700 dark:text-gray-300"><td class="px-6 py-4 font-bold text-gray-950 dark:text-white">{{ $purchase->user?->name ?? __('lms.instructor.course_view.deleted_user') }}</td><td class="px-6 py-4">{{ number_format((float)$purchase->price,2) }} EGP</td><td class="px-6 py-4">{{ $purchase->coupon_code ?: '—' }}</td><td class="px-6 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $purchase->payment_status === 'completed' ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-400' : ($purchase->payment_status === 'failed' ? 'bg-rose-100 text-rose-700' : 'bg-amber-100 text-amber-700') }}">{{ __('instructor.statuses.'.$purchase->payment_status) }}</span></td><td class="px-6 py-4 text-gray-500">{{ $purchase->purchased_at?->translatedFormat('M d, Y') }}</td></tr>@empty<tr><td colspan="5" class="px-6 py-12 text-center text-gray-500">{{ __('lms.instructor.course_view.no_purchases') }}</td></tr>@endforelse</tbody></table></div></section>
    </div>
</x-filament-panels::page>
